// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfxnxlgiaqqpjrwytifq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmeG54bGdpYXFxcGpyd3l0aWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDMxMTEsImV4cCI6MjA3MzU3OTExMX0.qN3IJbnqF3tvV6bqD24PP494p4Qfog297RL8ARfBs8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});